T2 - Valores duplicados (Alejandro)

In [34]:
import pandas as pd
import numpy as np
import seaborn as sns

df = df = pd.read_csv("titanic_limpio.csv")

In [35]:
df.duplicated().sum()

np.int64(116)

Cantidad de duplicados

In [36]:
df[df.duplicated()]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
47,1,3,female,28.0,0,0,7.7500,Q,Third,woman,False,Queenstown,yes,True
55,1,1,male,28.0,0,0,35.5000,S,First,man,True,Southampton,yes,True
76,0,3,male,28.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
77,0,3,male,28.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
87,0,3,male,28.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
878,0,3,male,28.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True

Ver filas duplicadas

In [37]:
df[df.duplicated(keep=False)]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,Southampton,no,True
23,1,1,male,28.0,0,0,35.5000,S,First,man,True,Southampton,yes,True
26,0,3,male,28.0,0,0,7.2250,C,Third,man,True,Cherbourg,no,True
28,1,3,female,28.0,0,0,7.8792,Q,Third,woman,False,Queenstown,yes,True
29,0,3,male,28.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
870,0,3,male,26.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
877,0,3,male,19.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
878,0,3,male,28.0,0,0,7.8958,S,Third,man,True,Southampton,no,True
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,Southampton,no,True
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,Southampton,no,True

Dos pasajeros pueden compartir muchos datos y eso no significa necesariamente que sean duplicados reales, así que conviene comprobamos antes de borrar lo que pandas considera duplicado

In [38]:
duplicados = df[df.duplicated(keep=False)].sort_values(by=list(df.columns))
duplicados

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,embark_town,alive,alone
633,0,1,male,28.0,0,0,0.0000,S,First,man,True,Southampton,no,True
815,0,1,male,28.0,0,0,0.0000,S,First,man,True,Southampton,no,True
64,0,1,male,28.0,0,0,27.7208,C,First,man,True,Cherbourg,no,True
295,0,1,male,28.0,0,0,27.7208,C,First,man,True,Cherbourg,no,True
252,0,1,male,62.0,0,0,26.5500,S,First,man,True,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
692,1,3,male,28.0,0,0,56.4958,S,Third,man,True,Southampton,yes,True
65,1,3,male,28.0,1,1,15.2458,C,Third,man,True,Cherbourg,yes,False
709,1,3,male,28.0,1,1,15.2458,C,Third,man,True,Cherbourg,yes,False
74,1,3,male,32.0,0,0,56.4958,S,Third,man,True,Southampton,yes,True
838,1,3,male,32.0,0,0,56.4958,S,Third,man,True,Southampton,yes,True

duplicated() compara todas las columnas. Si dos filas son exactamente iguales, pandas las considera duplicadas, pero eso no demuestra por sí solo que sean un error del dataset

In [39]:
df = df.drop_duplicates()

Una vez comprobados eliminamos duplicados

In [40]:
df.duplicated().sum()

np.int64(0)

Comprobación final

In [41]:
df.shape

(775, 14)

Resultado final tras limpieza + duplicados

In [42]:
df.to_csv("titanic_limpio.csv", index=False)