T3 - Comlumnas nuevas con numpy (Angel David)

In [12]:
import pandas as pd
import numpy as np
import seaborn as sns

df = pd.read_csv("titanic_limpio.csv")

In [19]:
df["franja_edad"] = np.select(
    [
        df["age"] < 18,
        df["age"] < 60,
        df["age"] >= 60
    ],
    [
        "Menor",
        "Adulto",
        "Mayor"
    ],
    default="Desconocido"
)

In [20]:
df[["age", "franja_edad"]].head(20)

     age franja_edad
0   22.0      Adulto
1   38.0      Adulto
2   26.0      Adulto
3   35.0      Adulto
4   35.0      Adulto
5   28.0      Adulto
6   54.0      Adulto
7    2.0       Menor
8   27.0      Adulto
9   14.0       Menor
10   4.0       Menor
11  58.0      Adulto
12  20.0      Adulto
13  39.0      Adulto
14  14.0       Menor
15  55.0      Adulto
16   2.0       Menor
17  28.0      Adulto
18  31.0      Adulto
19  28.0      Adulto

In [21]:
df["franja_edad"].value_counts()

franja_edad
Adulto    640
Menor     110
Mayor      25
Name: count, dtype: int64

In [23]:
df["franja_edad"].value_counts(normalize=True) * 100

franja_edad
Adulto    82.580645
Menor     14.193548
Mayor      3.225806
Name: proportion, dtype: float64

In [24]:
df.shape

(775, 15)

In [25]:
df["familiares"] = df["sibsp"] + df["parch"]

In [26]:
df[["sibsp", "parch", "familiares"]].head(10)

   sibsp  parch  familiares
0      1      0           1
1      1      0           1
2      0      0           0
3      1      0           1
4      0      0           0
5      0      0           0
6      0      0           0
7      3      1           4
8      0      2           2
9      1      0           1

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 775 entries, 0 to 774
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     775 non-null    int64
 1   pclass       775 non-null    int64
 2   sex          775 non-null    str
 3   age          775 non-null    float64
 4   sibsp        775 non-null    int64
 5   parch        775 non-null    int64
 6   fare         775 non-null    float64
 7   embarked     775 non-null    str
 8   class        775 non-null    str
 9   who          775 non-null    str
 10  adult_male   775 non-null    bool
 11  embark_town  775 non-null    str
 12  alive        775 non-null    str
 13  alone        775 non-null    bool
 14  franja_edad  775 non-null    str
 15  familiares   775 non-null    int64
dtypes: bool(2), float64(2), int64(5), str(7)
memory usage: 86.4 KB

Se ha creado la columna franja_edad mediante la función np.select() de NumPy. Esta nueva variable permite clasificar a los pasajeros en tres grupos según su edad: menores de 18 años, adultos entre 18 y 59 años y mayores de 60 años.

También se ha creado la columna familiares, calculada a partir de la suma de las columnas sibsp y parch. Esta variable representa el número de familiares que viajaban con cada pasajero según los datos disponibles.

Estas transformaciones permiten trabajar posteriormente con grupos de edad y tamaño de familia durante el análisis exploratorio.

In [28]:
df.to_csv("titanic_limpio.csv", index=False)